version: '3.8'
services:
  backend:
    build: ./SmartAppointmentBackend
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build: ./smart-appointment-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

